### ISSUE TITLE
Clarify how to specify IngestionEndpoint

### ISSUE THREAD

**Issue by FrankMuehlschlegel** [kentcb/azure_application_insights#11]
Hello kentcb,

thank you for implementing this useful library. 
Could you please clarify hot specify the ingestionEndpoint i.e. https://germanywestcentral-0.in.applicationinsights.azure.com/
Perhaps it makes sense to support connection strings. "InstrumentationKey=aaaaaaaa-1111-2222-3333-dddddddddddd;IngestionEndpoint=https://germanywestcentral-0.in.applicationinsights.azure.com/"

Best regards
Frank

**Comment by kentcb** [comment]
Thanks for reporting and sorry for the delay. Life has been hectic. Will be in next release.
