### ISSUE TITLE
Device info is not being logged

### ISSUE THREAD

**Issue by begandroide** [kentcb/azure_application_insights#12]
Hi @kentcb, thanks for this usefull package, very simple to use in an interceptor of http request's.

Requests are being logged on Azure App insights but the device info show "PC", when the requests are sended from android phone.

Which configuration can be setted for this?

**Comment by kentcb** [comment]
Hi,

This is mentioned in README and detailed in the example, but I've added more info to the README.

**Comment by begandroide** [comment]
thanks you! now it is much clearer.
