### ISSUE TITLE
navigatorObservers for user engagement and navigation analytics 

### ISSUE THREAD

**Issue by toklive** [kentcb/azure_application_insights#13]
Is there a way to track the page navigation using an observer like how firebase analytics does using this package ?

FirebaseAnalytics analytics = FirebaseAnalytics();

MaterialApp(
  home: MyAppHome(),
  **navigatorObservers: [
    FirebaseAnalyticsObserver(analytics: analytics),**
  ],
);

**Comment by kentcb** [comment]
Sure, you just need to create your own `NavigatorObserver` that forwards events to a `TelemetryClient`. Something like:

```dart
lass TelemetryObserver extends NavigatorObserver {
  TelemetryObserver({
    @required this.telemetryClient,
  });

  final TelemetryClient telemetryClient;

  @override
  void didPush(Route<dynamic> route, Route<dynamic> previousRoute) {
    final routeName = route.settings.name ?? '<<unnamed route of type ${route.runtimeType}>>';

    telemetryClient.trackPageView(
      name: routeName,
      additionalProperties: <String, Object>{
        'previousName': previousRoute?.settings?.name,
      },
    );

    // Ensure any future telemetry items have the correct route name associated with them.
    telemetryClient.context.properties['routeName'] = routeName;
  }
}
```

Then pass that observer into your `MaterialApp`'s navigator observers.

Hope that helps

**Comment by saravp123** [comment]
Thanks @kentcb for the code.  Do you have any idea / thoughts on how we can track the duration the user has been in each page?  I see that there is a duration property in trackPageView for this but not sure how to populate this field

**Comment by kentcb** [comment]
@saravp123 you'd have to capture the time on `didPush`, then override the various other relevant methods such that they:

1. calculate the delta between now and when the page was pushed
2. pass that through to tracePageView
