### ISSUE TITLE
Way to use TelemetryHttpClient with Dio

### ISSUE THREAD

**Issue by dhirenships** [kentcb/azure_application_insights#14]
Hi, 
I have been using [Dio](https://pub.dev/packages/dio) for almost all network requests. I have been looking for a way to connect the client used by Dio with TelemetryClient.trackRequest to track HTTP requests sent by it. 

The problem is, Dio uses [dart's _http HttpClient](https://api.dart.dev/be/150543/dart-_http/HttpClient-class.html), and TelemetryClient takes in[ another kind of Client](https://pub.dev/documentation/http/latest/io_client/IOClient-class.html). So unable to connect the two together.

Any help will be appreciated.

**Comment by kentcb** [comment]
Hi,

The `Client` used by this package is from the [`http`](https://pub.dev/packages/http) package, but only the abstraction is depended upon. That is, you can pass any implementation of `Client` into the `TransmissionProcessor`. I don't really understand the relationship between `Client` and the `HttpClient` you linked, but there might be an adapter? Or if not, it might be fairly straightforward to write your own?

Let me know how you get on.
