### ISSUE TITLE
Way to increase the size of telemetry item sent

### ISSUE THREAD

**Issue by marmagno** [kentcb/azure_application_insights#18]
Good day!

Thank you for the great package, it has been useful to us for sending logs to azure app insights efficiently.

But there is an instance that we send somehow big data to AI and the package only allows 65536 of data bytes?.

Is there a way for us to increase the size? 

Here is a screenshot of a response:

![image](https://user-images.githubusercontent.com/15721307/127463441-2bc754ed-3b90-43b6-979d-b474ed1188b2.png)

**Comment by kentcb** [comment]
Thanks for the kind words, @marmagno. The 64KiB limit on telemetry items is server-imposed, so there's nothing a client library like this can do about it. For that and other limits, see [this documentation](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/azure-subscription-service-limits#application-insights).
