### ISSUE TITLE
How to trace graphql request by using TelemetryHttpClient() ?

### ISSUE THREAD

**Issue by yukitaka13-1110** [kentcb/azure_application_insights#22]
I want to trace http request.
I'm using graphql client, so I want to know how to trace it.

https://pub.dev/packages/graphql_flutter

**Comment by kentcb** [comment]
Sorry, I don't know anything about GraphQL and consider it outside the scope of this library. However, I would assume it has the ability to provide a custom `Client`. You're probably best checking with the GraphQL community.
