### ISSUE TITLE
How to set CloudRole Name 

### ISSUE THREAD

**Issue by toklive** [kentcb/azure_application_insights#23]
Is there a way to set the  CloudRoleName to see the instance in the Application Map ? In this SDK it is read only. Looking for something like below.

https://www.davepaquette.com/archive/2020/02/05/setting-cloud-role-name-in-application-insights.aspx

**Comment by kentcb** [comment]
Hi @toklive, is this what you're after? https://github.com/kentcb/azure_application_insights/blob/master/lib/src/context.dart#L77

Should be something like:

```dart
context.cloud.role = 'some role';
```
