### ISSUE TITLE
ai.user.id is not set correctly

### ISSUE THREAD

**Issue by HectorMeneses333** [kentcb/azure_application_insights#24]
Hi, 

The ai.user.id property is not set correctly. Right now it is using ai.user.userId. This does not get translated correctly in app insights and we end up showing only one user in app insights ( namely user with id empty ).

In context.dart change this:
static const _userIdKey = '${_prefix}userId';
to this:
static const _userIdKey = '${_prefix}id';

**Comment by kentcb** [comment]
@HectorMeneses333 Thanks for the report. I've published [a fix](https://pub.dev/packages/azure_application_insights/versions/2.1.1)
