### ISSUE TITLE
Using Telemetry Correlation correctly

### ISSUE THREAD

**Issue by HectorMeneses333** [kentcb/azure_application_insights#27]
Hi,

How is W3C distributed tracing support handled by this package?

[https://docs.microsoft.com/en-us/azure/azure-monitor/app/correlation](url)

I see there's support for operation.Id and operation.parentId but not sure how to use that correctly.
Could you expand on that?

Thanks!!

**Comment by kentcb** [comment]
Sorry, W3C distributed tracing is not something I know anything about and seems outside the scope of this package's goals. If there's some way in which you think this package should change to better align with W3CDT then please create a proposal with details on what should change and why. Thanks.
