### ISSUE TITLE
Possible to remove request header from TelemetryHttpClient

### ISSUE THREAD

**Issue by RCSandberg** [kentcb/azure_application_insights#33]
First: thanks for the package, works excellent!

From what I can see in the code, it is not possible at the moment to remove the request headers when using the TelemetryHttpClient. Am I correct in that assumption?

With the current implementation, the authorization bearer token is appended with the request headers (if such is used) when the telemetry client tracks the request. Would it be possible to have the option to not add request headers to the additional properties when using the TelemetryHttpClient?

**Comment by RCSandberg** [comment]
I made a pull request ( #34 ) for the "feature" I'd like to have.

**Comment by RCSandberg** [comment]
It could also be made so that specifically 'Authorization' header isn't appended, or that it is configurable which "header-keys" not to append, if "don't-append-all-headers" is too broad..

**Comment by kentcb** [comment]
@RCSandberg thanks for the PR. I do think a single flag is too broad. Would you mind changing to allow call sites to optionally provide a header filter? i.e. a lambda/function of type `bool ForwardHeader(string header)`

**Comment by RCSandberg** [comment]
Good suggestion. I've updated the PR.

**Comment by kentcb** [comment]
Thanks very much for your contribution, @RCSandberg

**Comment by RCSandberg** [comment]
@kentcb Is it possible for you do make a release with the added feature? I'm currently pointing to the git hash... so no rush, but would be nice to have a released version.

**Comment by kentcb** [comment]
@RCSandberg 3.1.0 is now released. Thanks again.
