### ISSUE TITLE
pubspec yaml conflicts with flutter_test

### ISSUE THREAD

**Issue by haidarmehsen** [kentcb/azure_application_insights#41]
```
Because every version of flutter_test from sdk depends on stack_trace 1.11.0 and azure_application_insights >=4.0.0 depends on stack_trace ^1.11.1, flutter_test from sdk is incompatible with azure_application_insights >=4.0.0.
So, because ... depends on both azure_application_insights ^4.0.0 and flutter_test from sdk, version solving failed.
```
Hello, I tried using this package in my app but got this error, also tried to downgrade to 3.1.0 but got similar error about http. what can I do to use this package?

**Comment by m-gug** [comment]
@kentcb also having troubles updating to version 4.0.0 because of a dependency conflict on stack_trace.
Could you maybe downgrade the stack_trace dependency to 1.11.0 instead of 1.11.1?

**Comment by ManuelRauber** [comment]
Same issue here. Would be nice, if you can fix it @kentcb

**Comment by luizrmm** [comment]
Same issue here, can you fix please? @kentcb
