### ISSUE TITLE
Scoped Operations?

### ISSUE THREAD

**Issue by Leonardo-Ferreira** [kentcb/azure_application_insights#49]
Are there any plans to support an api like "TelemetryClient.StartOperation"?

My need is due to the fact that I start several operations in parallel like "Refresh Best Sellers", "Refresh Recommendations", "Refresh Recently Added", "Refresh Flash Sales" and because the context is unique, they all end-up with the same operation name, the same operation id and etc

**Comment by kentcb** [comment]
No plans. Can you not just use a separate TelemetryClient with its own context? Closing for now, and would need clear description of the problem to help any further.
