### ISSUE TITLE
Http requests should be tracked as dependency events

### ISSUE THREAD

**Issue by kbublitz** [kentcb/azure_application_insights#50]
When using the TelemetryHttpClient to track requests, a "Request" event is tracked for every request. But according to the [Data Model](https://learn.microsoft.com/en-us/azure/azure-monitor/app/data-model-complete), outgoing requests should be tracked as "Dependency" instead.

There already is a PR #46 that adds a trackDependency functionality. In addition I suggest that the TelemetryHttpClient should use that trackDependency instead of trackRequest as the default way of tracking outgoing HTTP requests.

I'm aware that this might be a breaking change for people who are already using the library and are evaluating the Request events in AI, but it would overall result in a cleaner reporting.

**Comment by kentcb** [comment]
Thanks, fixed by #55

**Comment by ManuelRauber** [comment]
Hey @kentcb 

Can you also update the package on pub.dev? There is only version 4.0.1 available that does not contain that change.

Thanks!

**Comment by kentcb** [comment]
@ManuelRauber Updated
