### ISSUE TITLE
Add Connection String Support

### ISSUE THREAD

**Issue by netsy** [kentcb/azure_application_insights#53]
Azure Application Insights will [end support for instrumentation key on 2025](https://learn.microsoft.com/en-us/azure/azure-monitor/app/sdk-connection-string?tabs=dotnet5). Auzre recommends transitioning to connection strings to take advantage of new capabilities.

I am studying a [PR](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/28854) from OpenTelemetry to explore the possibility of adding support for connection strings in `azure_application_insights`. Do you have any insights on this matter?

**Comment by m-gug** [comment]
@netsy I've also been wondering whether adjustments are needed here to switch to the connection string.
I've now looked at the official JS Application Insights SDK and it looks to me as if the connection string is only parsed and the InstrumentationKey contained in it is still in the transmitted events in 'iKey' (https://github.com/microsoft/ApplicationInsights-JS/blob/6ec22e829d568892bb005beefcc245471a7d788b/tools/applicationinsights-web-snippet/src/snippet.ts#L97).
Only the ingestion endpoint would also be parsed.

But we can already specify a different ingestion endpoint in the TransmissionProcessor, so I don't think any adjustments are necessary at the moment, or am I missing something?

**Comment by kentcb** [comment]
See #56
