### ISSUE TITLE
trackEvent vs. trackTrace

### ISSUE THREAD

**Issue by SogoGolf** [kentcb/azure_application_insights#7]
hey @kentcb , thanks a ton for this package !! is super helpful and we've wired it up into our app. 

dumb question I know (new to using App Insights) but what is the difference between "trackEvent" and "trackTrace" ? I know they show up separately in App Insights (as a trace or event) but I'm just wondering what the diff is and why would I care? if you can just give me a really quick answer that would be awesome (Microsoft docs can be like wading into an endless haystack looking for the needle...)

**Comment by kentcb** [comment]
Hey @SogoGolf, I know exactly what you mean about trying to discern the differences between these "buckets" of data. At the end of the day, it seems to me you could almost store anything anywhere and it's really just convention that dictates what would ordinarily go where. I've never seen anything to confirm this, but I suspect all buckets are exactly the same behind the scenes and what differs is Azure's default view of those buckets (what columns it display by default).

That said, there are some pretty good docs [here](https://docs.microsoft.com/en-us/azure/azure-monitor/app/data-model) that cover the data model and what you should typically put in each bucket.

**Comment by SogoGolf** [comment]
Perfect that's what I thought too, thanks @kentcb
