### ISSUE TITLE
send telemetry without delay

### ISSUE THREAD

**Issue by SogoGolf** [kentcb/azure_application_insights#8]
hey @kentcb , I've got a need to send telemetry logs without any delay. ie. as you note in your readme - _"...and a second that does not buffer and is used only to submit errors as promptly as possible."_

I couldn't see how to configure that. Could you please let me know here (I might also add that to the readme for others as a quick reference).

**Comment by kentcb** [comment]
@SogoGolf To send without delay, you can elide the `BufferedProcessor` from your processor chain:

```dart
final processor = TransmissionProcessor(
  instrumentationKey: instrumentationKey,
  httpClient: client,
  timeout: const Duration(seconds: 10),
);

final telemetryClient = TelemetryClient(
  processor: processor,
);
```
Doing so will cause telemetry items to be transmitted immediately rather than buffering them until some maximum number or timeout is reached.

**Comment by SogoGolf** [comment]
perfect thanks @kentcb
